### ISSUE TITLE
编译时报错：Error: Error: Unexpected token

### ISSUE THREAD

**Issue by GangRock** [Qquanwei/trackpoint-tools#1]
想试试，但编译时报错：

Error: Error: Unexpected token
index.js (4:10)
2: 
3: class SomeComponent {
4:   onClick = after(() => console.log('send after'))(() => {
^
5:     // normal
6:     console.log('normal click')

**Comment by Qquanwei** [comment]
Hi, 这个问题是因为默认的jsx不支持直接写成这种语法。
可以用babel转换一下: https://babeljs.io/docs/plugins/transform-class-properties/

或者写成
```
class SomeComponent {
   @track(after(() => {}))
   onClick () {
   }
}
```

**Comment by GangRock** [comment]
@Qquanwei hi~ 这个工具可否用于MUI开发的APP里？谢谢！

**Comment by Qquanwei** [comment]
@GangRock 理论上这只是一个单纯的Javascript库，跟框架无关。 所以应该是可行的，但是我没试过

**Comment by GangRock** [comment]
@Qquanwei 谢谢！

**Comment by GangRock** [comment]
@Qquanwei  可否写一个应用的例子呢？

**Comment by Qquanwei** [comment]
@GangRock 
https://gist.github.com/Qquanwei/fc53c49179256e0a41a86e3131cda9e0
