### ISSUE TITLE
vue3 reports an error when using this plug-in

### ISSUE THREAD

**Issue by lzdml** [Qquanwei/trackpoint-tools#16]
<img width="1392" alt="image" src="https://github.com/Qquanwei/trackpoint-tools/assets/137750167/df303eda-b6a6-40cc-8118-4e658b249c9a">

**Comment by Qquanwei** [comment]
根据错误信息，需要在vite配置中开启装饰器的支持

参考下这篇解决方案：https://stackoverflow.com/questions/66395054/how-do-i-enable-babel-plugin-proposal-decorators-with-vite
