### ISSUE TITLE
增加 Vue / React 示例

### ISSUE THREAD

**Issue by Maple13** [Qquanwei/trackpoint-tools#3]
您好! 不知道有没有增加 Vue / React 示例的计划呢?

**Comment by Qquanwei** [comment]
是我的疏忽，之前一直没加， 近期内加上 . :D

**Comment by Maple13** [comment]
谢谢! 近期准备在 react 中使用, 试了一下 after / before / evolve / composeWith / createCounter, 有些还是感觉茫然

**Comment by Qquanwei** [comment]
@Maple13  https://codesandbox.io/s/wqxr0j2qj5

这里提供了一个React的示例，提供了一些常规的用法。(更多示例也可以参考test目录下的appSpec.js)

因为此库无关框架，只是纯JS, 所以React/Vue的写法上并没有很大分别

**Comment by Maple13** [comment]
好的👌, 感谢您的付出
