### ISSUE TITLE
在方法devide = (a, b) => {}上trackpoint执行没有效果，不起作用

### ISSUE THREAD

**Issue by cyranosky** [Qquanwei/trackpoint-tools#4]
class A {
    @track(before(() => console.log('this is add')))
    add(a, b){
      return a + b
    }

    @track(before(() => console.log('this is devide')))
    devide = (a, b) => {
      return a / b
    }
}

如上定义的类，add方法上trackpoint可以打出日志(this is add)，但是devide = (a, b) => {}方式定义的方法trackpoint不起作用。

请问trackpoint可以支持这种方法定义吗？   devide = (a, b) => {}

**Comment by Qquanwei** [comment]
感谢反馈，已经在 [0.0.10](https://www.npmjs.com/package/trackpoint-tools)中修复.
