### ISSUE TITLE
看vue 示例demo有报错的警告，是什么原因，如何解决？

### ISSUE THREAD

**Issue by TroyIrvo** [Qquanwei/trackpoint-tools#6]
![Uploading image.png…]()

**Comment by Qquanwei** [comment]
没有发现错误信息，而且截图也看不到，可以重新发下截图。

**Comment by TroyIrvo** [comment]
Parsing error: Stage 2 decorators disallow object literal property decorators 14 | }, 15 | methods: { > 16 | @track(before(() => console.log("click before"))) | ^ 17 | onClickButton() { 18 | console.log("click button", this.name); 19 | } (null)

**Comment by Qquanwei** [comment]
我在最新版的Chrome以及Firefox上均没有看到改提示，如果是你自己项目中用到的话需要加一个Plugin

```  
"plugins": [
     ...
    "transform-decorators-legacy"
  ]
```

**Comment by TroyIrvo** [comment]
[image: TIM截图20190711094037.png]
可能我的浏览器不是最新的。我在自己项目里面加了这个。但是好像不起作用。

Qquanwei <notifications@github.com> 于2019年7月10日周三 下午1:22写道：
