### ISSUE TITLE
是否可以添加下.d.ts文件？

### ISSUE THREAD

**Issue by liubr1491** [Qquanwei/trackpoint-tools#7]
ts引入trackpoint-tools比较费劲，可否添加下.d.ts文件？

**Comment by Qquanwei** [comment]
应该加上的，我来加下

**Comment by Qquanwei** [comment]
已经加上了一个基础type.d文件, release trackpoint-tools@0.1.0。顺便优化了下构建，老的构建方式性能有问题。
